### ISSUE TITLE
Cannot use passkeys with non-default panel

### ISSUE THREAD

**Issue by austincarpenter** [rawilk/profile-filament-plugin#20]
### profile-filament-plugin Version

v0.3.2

### Laravel Version

v10.46

### Bug description

Adding a passkey fails in a panel other than the default one. This is because a 403 occurs on the client side when fetching `/sessions/webauthn/attestation-pk`. Somewhere in this flow I believe the 'current panel' is resolved, erroneously returning the default one which in my instance the user does not have access **to.******

### Steps to reproduce

As above.

**Comment by rawilk** [comment]
I noticed that too, however I haven't had a chance to properly deal with it yet.

**Comment by rawilk** [comment]
I've had some time to update the package this last week, and I found what the issue is. The webauthn routes for retrieving the attestation options were wrapped in Filament's Authenticate middleware, instead of Laravel's. Since these routes aren't associated with a given panel, Filament's middleware was using the default panel to verify a user has access to. After switching to Laravel's Authenticate middleware for these routes, this issue should be gone.
